import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteGuard from "../containers/RouteGuard";
import Sidebar from "@/components/organisms/Sidebar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* bg-dark */}
      <body className=" min-h-screen">
        {/* Sidebar fixed */}
        {/* <Sidebar /> */}

        {/* Main content area */}
        <main className=" flex justify-center">
        {/* px-10 pl-60 */}
          <div className="w-full max-w-[1200px] ">
            <RouteGuard>
              {children}
            </RouteGuard>
          </div>
        </main>
        
        
        
        
        
        <Script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js" />
        <Script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" />
      </body>
    </html>
  );
}
