import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteGuard from "../containers/RouteGuard";
import Sidebar from "@/components/organisms/Sidebar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-dark">
        <Sidebar/>
        <div className="ml-60 py-5 px-5">
          <RouteGuard>
            {children}
          </RouteGuard>
          
          <footer className="h-28 rounded-lg shadow bg-gray-800">
            <div className="w-full mx-auto  md:p-6 p-4 md:flex md:items-center md:justify-between">
              <span className="text-sm sm:text-center text-gray-400">© Craftly made by <a
                  href="https://macnesa.com/" className="hover:underline font-semibold">macnesa</a>. This app used Spotify
                Official API to access your data.
              </span>
              <ul className="flex flex-wrap items-center mt-3 text-sm text-gray-400 sm:mt-0">
                <li>
                  <a href="https://developer.spotify.com/documentation/web-api/" className="mr-4 hover:underline md:mr-6 ">Spotify
                    API</a>
                </li>
                <li>
                  <a href="https://developer.spotify.com/policy/" className="mr-4 hover:underline md:mr-6">Privacy Policy</a>
                </li>
                <li>
                  <a href="https://github.com/macnesa" className="mr-4 hover:underline md:mr-6">Visit My Github</a>
                </li>
                <li>
                  <a href="https://www.instagram.com/macnesa_/" className="hover:underline">My Ig</a>
                </li>
              </ul>
            </div>
          </footer>
          
        </div>
        
        
        
        
        
        
        <Script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js" />
        <Script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" />
      </body>
    </html>
  );
}
